
name: Render presentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1

    - name: Cache packages
      uses: actions/cache@v2
      with:
        path: ~/.local/share/renv
        key: renv-${{ hashFiles('renv.lock') }}
        restore-keys: renv-
        
    - name: Install linux dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
 
    - name: Restore packages
      shell: Rscript {0}
      run: |
        if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
        renv::restore()

    - name: Render presentation
      run: 	R -e 'rmarkdown::render("presentation.Rmd", output_file = "index.html")'

    - name: Commit results
      run: |
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git commit index.html -m 'Re-build presentation' || echo "No changes to commit"
        git push origin || echo "No changes to commit"